dist: xenial
language: python

env:
  global:
    - PYTEST_ADDOPTS="-s -vv --cov --cov-report=xml"

jobs:
  include:
    - os: osx
      osx_image: xcode10.2
      language: generic
      env: TOXENV=py37-coverage
      before_install:
        - ln -sfn "$(which python3)" /usr/local/bin/python
        - python -V
        - test $(python -c 'import sys; print("%d%d" % sys.version_info[0:2])') = 37

    # Fails currently badly.
    # - python: '3.7'
    #   env: TOXENV=qa

install:
  - pip install tox

script:
  - tox

after_script:
  - |
    if [[ "${TOXENV%-coverage}" != "$TOXENV" ]]; then
      bash <(curl -s https://codecov.io/bash) -Z -X gcov -X coveragepy -X search -X xcode -X gcovout -X fix -f coverage.xml -n $TOXENV -F "${TRAVIS_OS_NAME}"
    fi

# Only master and releases.  PRs are used otherwise.
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/
